config/routes.rb
PaisaFinder2::Application.routes.draw do
	resources :users			
	resources :sessions, only: [:new, :create, :destroy]
	resources :states do
		resources :municipalities, except: :index 
	end	

  resources :municipalities do
    resources :towns, except: :index
  end  

  resources :towns do
    resources :posts, except: :index
  end  

	root to: 'static_pages#home'

	match '/signup',  to: 'users#new'
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

	match '/help',    to: 'static_pages#help'
	match '/about',   to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'

end

app/models/state.rb
class State < ActiveRecord::Base
  attr_accessible :name

	has_many :municipalities, dependent: :destroy 

	validates :name, presence: true

	default_scope order: 'states.name ASC'
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
	before_filter :admin_user, except: :show

	def show
		@state = State.find(params[:id])				
		@municipalities = @state.municipalities.paginate(page: params[:page])
	end

	def index
		@states = State.all	
	end

	def new
		@state = State.new
	end
	
	def create
		@state = State.new(params[:state])
		if @state.save
			flash[:success] = "New state created"			
			redirect_to states_url
		else
			render 'new'
		end
	end	

	def edit
		@state =	State.find(params[:id]) 
	end	

	def update	
		@state = State.find(params[:id])
		if @state.update_attributes(params[:state])
			flash[:success] = "State updated"
			redirect_to states_url
		else
			render 'edit'
		end	
	end	

	def destroy
		State.find(params[:id]).destroy
		flash[:success] = "State destroyed."
		redirect_to states_url
	end	

	private
		def admin_user
			@user = User.find_by_remember_token(cookies[:remember_token])
			if @user && @user.admin?
				true
			else	
				redirect_to(root_path)
			end	
		end	

end	

app/views/states/_state.html.erb
<li>
<%= link_to state.name, state %> 
	<% if signed_in? && @current_user.admin? %>
		| <%= link_to "delete", state, method: :delete,
																	 data: { confirm: "You sure?" } %> |
		<%= link_to "edit", edit_state_path(state) %>
	<% end %>	
</li>

app/views/states/edit.html.erb
<% provide(:title, 'Edit state') %>
<h1>Update state</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@state) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
		
			<%= f.label :name %>
			<%= f.text_field :name %>			

			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>	

app/views/states/index.html.erb
<% provide(:title, 'All states') %>
<h1>All states</h1>

<ul class="states">
	<%= render @states %>
</ul>	

app/views/states/new.html.erb
<% provide(:title, 'Create new state') %>
<h1>Create new state</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@state) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>
		
			<%= f.label :name %>
			<%= f.text_field :name %>			

			<%= f.submit "Create new state", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>	

app/views/states/show.html.erb
<% provide(:title, @state.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1><%= @state.name %></h1>
		</section>
	</aside>
	<div class="span8">
		<% if @state.municipalities.any? %>
			<h3>Municipalities (<%= @state.municipalities.count %>)</h3>
			<ol class="municipalities">
				<%= render @municipalities %>
			</ol>
			<%= will_paginate @municipalities %>
		<% end %>
	</div>		
</div>	
							