config/routes.rb
PaisaFinder2::Application.routes.draw do
	resources :users			
	resources :sessions, only: [:new, :create, :destroy]
	resources :states do
		resources :municipalities, except: :index 
	end	

  resources :municipalities do
    resources :towns, except: :index
  end  

  resources :towns do
    resources :posts, except: :index
  end  

	root to: 'static_pages#home'

	match '/signup',  to: 'users#new'
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

	match '/help',    to: 'static_pages#help'
	match '/about',   to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'

end

app/models/municipality.rb
class Municipality < ActiveRecord::Base
  attr_accessible :name
	belongs_to :state
  has_many :towns, dependent: :destroy

	validates :name,     presence: true
	validates :state_id, presence: true 
	
	default_scope order: 'municipalities.name ASC'
end

app/controllers/municipalities_controller.rb
class MunicipalitiesController < ApplicationController
	before_filter :admin_user, except: :show
	before_filter :get_state			

	def get_state
		@state = State.find(params[:state_id])
	end

	def show
		@municipality = @state.municipalities.find(params[:id])
    @towns = @municipality.towns.paginate(page: params[:page])
	end	

	def new
  	@municipality = @state.municipalities.new
	end	
	
	def create
		@municipality = @state.municipalities.new(params[:municipality])
		if @municipality.save
			flash[:success] = "Municipality created!"
			redirect_to @state
		else
			render 'new'
		end	
	end

	def edit
		@municipality = @state.municipalities.find(params[:id])
	end				

	def update
		@municipality = @state.municipalities.find(params[:id])
		if @municipality.update_attributes(params[:municipality])
			flash[:success] = "Municipality updated"
			redirect_to @state
		else
			render 'edit'
		end	
	end				

	def destroy
		@municipality = @state.municipalities.find(params[:id])
		@municipality.destroy
		redirect_to @state		
	end

	private

		def admin_user
			@user = User.find_by_remember_token(cookies[:remember_token])
			if @user && @user.admin?
				true
			else	
				redirect_to(root_path)
			end	
		end	
end	

app/views/municipalities/_municipality.html.erb
<li>
	<span class="name"><%= link_to municipality.name, [@state, municipality] %></span>
	<% if signed_in? && @current_user.admin? %>
		<%= link_to "delete", [@state, municipality], 
									        method: :delete,
													data: { confirm: "You sure?" } %> |
		<%= link_to "edit", edit_state_municipality_path(@state, municipality) %>
	<% end %>	
</li>	

app/views/municipalities/edit.html.erb
<% provide(:title, 'Update municipality') %>
<h1>Update municipality</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for([@state, @municipality]) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>			<% end %>
	</div>
</div>	

app/views/municipalities/new.html.erb
<% provide(:title, 'Create new municipality') %>
<h1>Create new municipality</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for([@state, @municipality]) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>

      <%= f.submit "Create new municipality", class: "btn btn-large btn-primary" %>		
    <% end %>
	</div>
</div>	

app/views/municipalities/show.html.erb
<% provide(:title, @municipality.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1><%= @municipality.name %></h1>
		</section>
	</aside>
  <div class="span8">
    <% if @municipality.towns.any? %>
      <h3>Towns (<%= @municipality.towns.count %>)</h3>
      <ol class="towns">
        <%= render @towns %>
      </ol>
      <%= will_paginate @towns %>
    <% end %>
  </div>  
</div>