config/routes.rb
PaisaFinder2::Application.routes.draw do
	resources :users			
	resources :sessions, only: [:new, :create, :destroy]
	resources :states do
		resources :municipalities, except: :index 
	end	

  resources :municipalities do
    resources :towns, except: :index
  end  

  resources :towns do
    resources :posts, except: :index
  end  

	root to: 'static_pages#home'

	match '/signup',  to: 'users#new'
	match '/signin',  to: 'sessions#new'
	match '/signout', to: 'sessions#destroy', via: :delete

	match '/help',    to: 'static_pages#help'
	match '/about',   to: 'static_pages#about'
	match '/contact', to: 'static_pages#contact'

end

app/models/town.rb
class Town < ActiveRecord::Base
  attr_accessible :name

  belongs_to :municipality
  has_many :posts, dependent: :destroy

  validates :name, presence: true
  validates :municipality_id, presence: true

  default_scope order: 'towns.name ASC'
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  before_filter :admin_user, except: :show
	before_filter :get_municipality 
  before_filter :get_state 

  def show 
    @town = @municipality.towns.find(params[:id])
    @posts = @town.posts.paginate(page: params[:page])
  end

  def new
    @town = @municipality.towns.new  
  end

  def create 
    @town = @municipality.towns.new(params[:town]) 
    if @town.save
      flash[:success] = "Town created!"
      redirect_to [@state, @municipality]
    else
      render 'new'
    end  
  end

  def edit
    @town = @municipality.towns.find(params[:id])
  end

  def update
    @town = @municipality.towns.find(params[:id])
    if @town.update_attributes(params[:town])
      flash[:success] = "Town updated"
      redirect_to [@state, @municipality]
    else
      render 'edit'
    end
  end  

  def destroy
    @town = @municipality.towns.find(params[:id])
    @town.destroy
    redirect_to [@state, @municipality]
  end  

  private
	  def get_municipality
		  @municipality = Municipality.find(params[:municipality_id])
	  end

    def get_state
      @state = @municipality.state
    end  

    def admin_user
      @user = User.find_by_remember_token(cookies[:remember_token])
      if @user && @user.admin?
        true
      else
        redirect_to(root_path)
      end
    end  
end  

app/views/towns/_town.html.erb
<li>
  <span class="content"><%= link_to town.name, [@municipality, town] %></span>
	<% if signed_in? && @current_user.admin? %>
		<%= link_to "delete", [@municipality, town], 
									        method: :delete,
													data: { confirm: "You sure?" } %> |
		<%= link_to "edit", edit_municipality_town_path(@municipality, town) %>
	<% end %>	
</li>  

app/views/towns/edit.html.erb
<% provide(:title, 'Update town') %>
<h1>Update town</h1>

<div class="row">
  <div class="span6 offset3">
		<%= form_for([@municipality, @town]) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>			
    <% end %>
	</div>
</div>	

app/views/towns/new.html.erb
<% provide(:title, 'Create new town') %>
<h1>Create new town</h1>

<div class="row">
  <div class="span6 offset3">
		<%= form_for([@municipality, @town]) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>

      <%= f.submit "Create new town", class: "btn btn-large btn-primary" %>			
    <% end %>
	</div>
</div>	

app/views/towns/show.html.erb
<% provide(:title, @town.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1><%= @town.name %></h1>
    </section>  
  </aside>
  <div class="span8">
    <% if @town.posts.any? %>
      <h3>Posts (<%= @town.posts.count %>)</h3>
      <ol class="posts">
        <%= render @posts %>
      </ol>
      <%= will_paginate @posts %>
    <% end %>
  </div>  
</div>  